using System.Net;
using System.Net.Mail;
using IncidentResolution.Core.Configuration;
using IncidentResolution.Core.Interfaces;
using IncidentResolution.Core.Models;
using Microsoft.Extensions.Options;

namespace IncidentResolution.API.Services;

/// <summary>
/// Email service using SMTP
/// </summary>
public class EmailService : IEmailService
{
    private readonly EmailSettings _settings;
    private readonly ILogger<EmailService> _logger;

    public EmailService(IOptions<EmailSettings> settings, ILogger<EmailService> logger)
    {
        _settings = settings.Value;
        _logger = logger;
    }

    public async Task<bool> SendResolutionEmailAsync(string incidentDescription, List<Resolution> resolutions)
    {
        try
        {
            var htmlBody = BuildEmailBody(incidentDescription, resolutions);

            using var smtpClient = new SmtpClient(_settings.SmtpServer, _settings.SmtpPort)
            {
                EnableSsl = _settings.EnableSsl,
                DeliveryMethod = SmtpDeliveryMethod.Network
            };

            // Add credentials if username is provided
            if (!string.IsNullOrEmpty(_settings.Username))
            {
                smtpClient.Credentials = new NetworkCredential(_settings.Username, _settings.Password);
            }
            else
            {
                // Use default credentials (Windows authentication)
                smtpClient.UseDefaultCredentials = true;
            }

            var fromAddress = new MailAddress(_settings.SenderEmail, _settings.SenderDisplayName);
            var toAddress = new MailAddress(_settings.FinanceDistributionList);

            using var message = new MailMessage(fromAddress, toAddress)
            {
                Subject = $"Incident Resolution Recommendations - {DateTime.Now:yyyy-MM-dd HH:mm}",
                Body = htmlBody,
                IsBodyHtml = true
            };

            await smtpClient.SendMailAsync(message);

            _logger.LogInformation("Resolution email sent to {Recipient}", _settings.FinanceDistributionList);
            return true;
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Failed to send resolution email via SMTP");
            return false;
        }
    }

    private string BuildEmailBody(string incidentDescription, List<Resolution> resolutions)
    {
        var html = $@"
<!DOCTYPE html>
<html>
<head>
    <style>
        body {{ font-family: 'Open Sans', Arial, sans-serif; color: #333; }}
        .header {{ background: #DC6901; color: white; padding: 15px; }}
        .container {{ padding: 20px; }}
        .resolution {{ background: #f5f5f5; border-left: 4px solid #DC6901; padding: 15px; margin: 15px 0; }}
        .rank {{ font-size: 24px; font-weight: bold; color: #DC6901; }}
        .title {{ font-size: 18px; font-weight: 600; margin: 10px 0; }}
        .steps {{ margin-left: 20px; }}
        .steps li {{ margin: 5px 0; }}
        .confidence {{ color: #666; font-size: 12px; }}
    </style>
</head>
<body>
    <div class='header'>
        <h2>🔧 Incident Resolution Recommendations</h2>
    </div>
    <div class='container'>
        <h3>Incident Description:</h3>
        <p>{System.Web.HttpUtility.HtmlEncode(incidentDescription)}</p>
        <hr/>
        <h3>Top {resolutions.Count} Recommended Resolutions:</h3>";

        foreach (var resolution in resolutions)
        {
            html += $@"
        <div class='resolution'>
            <span class='rank'>#{resolution.Rank}</span>
            <span class='confidence'>(Confidence: {resolution.ConfidenceScore:P0})</span>
            <div class='title'>{System.Web.HttpUtility.HtmlEncode(resolution.Title)}</div>
            <p>{System.Web.HttpUtility.HtmlEncode(resolution.Description)}</p>
            <strong>Steps:</strong>
            <ul class='steps'>";
            
            foreach (var step in resolution.Steps)
            {
                html += $"<li>{System.Web.HttpUtility.HtmlEncode(step)}</li>";
            }
            
            html += $@"
            </ul>
            <p class='confidence'>Source: {resolution.SourceIncidentNumber} | Category: {resolution.Category}</p>
        </div>";
        }

        html += @"
        <hr/>
        <p style='color:#666; font-size:12px;'>This email was generated by the Incident Resolution Assistant.</p>
    </div>
</body>
</html>";

        return html;
    }
}

