'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class AnalystReport
    
    '''<summary>
    '''phStylesAndScripts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents phStylesAndScripts As Global.System.Web.UI.WebControls.PlaceHolder
    
    '''<summary>
    '''AnalystForm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AnalystForm As Global.System.Web.UI.HtmlControls.HtmlForm
    
    '''<summary>
    '''ResponsiveADHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ResponsiveADHeader As Global.Ashley.Web.Responsive.ResponsiveADHeader
    
    '''<summary>
    '''Navigation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Navigation As Global.EPay.EpayNav
    
    '''<summary>
    '''lblErrorMsg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblErrorMsg As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tblSearchInvoices control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblSearchInvoices As Global.System.Web.UI.WebControls.Table
    
    '''<summary>
    '''lstTerritory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstTerritory As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''txtCustomerNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCustomerNumber As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtConfirmationNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtConfirmationNo As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtReferenceNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtReferenceNo As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDate As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''cmdSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdSearch As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''grvReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grvReport As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''ResponsiveADFooter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ResponsiveADFooter As Global.Ashley.Web.Responsive.ResponsiveADFooter
    
    '''<summary>
    '''hdnSortColumn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnSortColumn As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdnSortAscending control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnSortAscending As Global.System.Web.UI.WebControls.HiddenField
End Class
