'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class EpayNav
    
    '''<summary>
    '''liEpayHome control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents liEpayHome As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''hlEpayHome control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlEpayHome As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''liUserList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents liUserList As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''hlUserList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlUserList As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''liAdminMaintenance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents liAdminMaintenance As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''hlAdminMaintenance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlAdminMaintenance As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''liReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents liReport As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''hlReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlReport As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''hlHistory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlHistory As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''hlHelp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlHelp As Global.System.Web.UI.WebControls.HyperLink
End Class
